# Generated by Django 5.1.7 on 2025-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_alter_patienthistory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_names', models.CharField(max_length=255)),
                ('typical_use', models.TextField()),
                ('price_range', models.CharField(max_length=255)),
                ('image_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
