# Generated by Django 5.1.7 on 2025-03-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0014_medicine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
