# Generated by Django 5.1.7 on 2025-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0020_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelabtest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
