# Generated by Django 5.1.7 on 2025-03-22 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0024_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('blood_pressure', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('predicted_health_condition', models.CharField(max_length=100)),
                ('health_risk', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
