# Generated by Django 5.1.7 on 2025-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0025_healthpredictionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpredictionhistory',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthpredictionhistory',
            name='blood_sugar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthpredictionhistory',
            name='cholesterol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthpredictionhistory',
            name='health_risk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='healthpredictionhistory',
            name='predicted_health_condition',
            field=models.CharField(max_length=255),
        ),
    ]
