# Generated by Django 5.1.7 on 2025-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0026_alter_healthpredictionhistory_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/doctors/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/patients/'),
        ),
    ]
