# Generated by Django 5.1.7 on 2025-03-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_app", "0027_doctorprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
