# Generated by Django 5.1.7 on 2025-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_app", "0028_patientprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="dosage_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_prescription_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicine",
            name="prescription_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="side_effects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="storage_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="warnings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
